### ISSUE TITLE
[Suggestion] Add ModActions.registerAction versions that work directly with ActionPerformer and BehaviourProvider

### ISSUE THREAD

**Issue by bdew** [ago1024/WurmServerModLauncher#16]
Currently if you have ActionPerformer separate from BehaviourProvider (e.g. if you want to put multiple actions in a submenu), registering them looks silly. Moreover you need to implement dummy behabiour providers on all ModActions even if they do nothing since getBehaviourProvider call is not checked for null return in registerAction.

It would be nice to have additional methods (e.g. registerActionPerfomer / registerBehaviour) that take the appropriate interface and register it.

**Comment by ago1024** [comment]
Hi,

I haven't been able to look into it but I'll do the next days.
