### ISSUE TITLE
Missing sources for modloader-shared?

### ISSUE THREAD

**Issue by bdew** [ago1024/WurmServerModLauncher#21]
It looks like it was split off from the main code in 13307390f51d188226a4f901db7a784b3f780ed7, but the sources aren't in the project or anywhere else i could find.

**Comment by ago1024** [comment]
The project is in https://github.com/ago1024/WurmModLoaderShared

**Comment by bdew** [comment]
Derp! I guess i'm blind. I was looking on your repositores page but didn't see it >.>
