### ISSUE TITLE
Automaticly add steamVersion property to mod properties

### ISSUE THREAD

**Issue by ago1024** [ago1024/WurmServerModLauncher#24]
Mods should be able to select features depending on the server or client version. Extract version from SteamVersion and put the version string as "steamVersion" into the properties sent to the client

**Comment by Joedobo27** [comment]
Thank you ago. I really need to improve my github skills so I can help out with this kind of thing.

**Comment by ago1024** [comment]
https://github.com/ago1024/WurmModLoaderShared/commit/11dc46b696c5e8d8310c47f9e673f104ffd482fd
