### ISSUE TITLE
Exception in thread "JavaFX Application Thread"

### ISSUE THREAD

**Issue by Tolbin** [ago1024/WurmServerModLauncher#29]
Using version 0.24 I get this error when starting the server with ./modlauncher.sh. Server comes up fine and seems to be working but the launcher thinks the server is offline.

"Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException"

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Any ideas?

Startup log: [http://pastebin.com/V9VkVxge](http://pastebin.com/V9VkVxge)

**Comment by bdew** [comment]
Update your hitching post mod, it's an outdated version and causes the crash.

**Comment by Tolbin** [comment]
This fixed it. Sorry, thought I had updated all the mods.

Thank you,
Tolbin
