### ISSUE TITLE
Pieces missing...

### ISSUE THREAD

**Issue by Dynarev** [ago1024/WurmServerModLauncher#35]
I am not sure what happens, but everytime you commit different files don't make it to the source code. Example this time the HookManager isn't there.

this makes it a little discouraging to wan't to help you improve it and make more advancements.

Don't get me wrong, you rock, this thing is awesome. However when I do a git I like to get it all hahaha.

**Comment by ago1024** [comment]
Some files are shared between the server and client modloader and are in a separate repository:
https://github.com/ago1024/WurmModLoaderShared

**Comment by Dynarev** [comment]
A git should have everything needed to do a fork, and compile it. It is in my release jar, nevermind.....
