### ISSUE TITLE
Mod loading order

### ISSUE THREAD

**Issue by Goldenflamer** [ago1024/WurmServerModLauncher#39]
The order in which mods are loaded on Windows and Linux seems to differ.

In general it would be nice to get some way to define loading order or at least mention library mods somewhere, so they can be loaded first for the other mods which depend on those library mods.

**Comment by ago1024** [comment]
Work in progress
https://github.com/ago1024/WurmModLoaderShared/commit/622c4c94552551de11fdc86f9090c3a27011f66d

**Comment by ago1024** [comment]
Version v0.29
