### ISSUE TITLE
error setting up ingame map.

### ISSUE THREAD

**Issue by Kilem** [ago1024/WurmServerModLauncher#47]
Sorry to bother ya, I have spent a good 12hrs going over and over the setup for servermap ingame.  followed your custom map settings 6 times and still get this error on clients.

INFO: Added server pack A0553A65523FE3159852CCAF022C54E021E81492
SEVERE: Unexpected end of file from server
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.URL.openStream(URL.java:1045)
	at org.gotti.wurmonline.clientmods.serverpacks.PackDownloader.run(PackDownloader.java:35)
	at java.lang.Thread.run(Thread.java:745)

map.png is right size
mappings.txt has map.scallywags=scallywags.png.
saved as scallywags.jar
jar is in mods/myservermap
myservermap.properties  has serverPacks=scallywags.jar
db mapname has scallywags
server shows added, but clients get above error.
I tried disableing servermap mod to no avail.  

Hope you have an idea where I went wrong. pulling what lil hair i have left out.

**Comment by ago1024** [comment]
Are there any errors in the server.log file on the server?

**Comment by Kilem** [comment]
only errors in log is when i destroy items as gm.
happy to send log.
like i said ive been puzzled for a cpl days now. I even tried adding a spaces to the mapping.txt   IE... map.scallywags = scallywags.png instead of
map.scallywags=scallywags.png.

**Comment by ago1024** [comment]
Could you please send me both the server and the client log please.

**Comment by Kilem** [comment]
[server.log](https://github.com/ago1024/WurmServerModLauncher/files/1691707/server.log)
[client.log](https://github.com/ago1024/WurmServerModLauncher/files/1691708/client.log)

**Comment by ago1024** [comment]
remove the publicServerPort=3724 config option on the server. It creates download URLs which point to the game protocol server not the http server for downloading the packs.

Best use those settings:
```
# Using fixed port 8787 for server pack download
serverPort=8787
# Not required. Defaults to the same as serverPort
#publicServerPort=8787
# Not required. Uses the same network interface as the game protocol
#internalServerAddress=192.227.113.54
# Not required. Defaults to the internalServerAddress or game server address respectively
#publicServerAddress=192.227.113.54
```

The pack download URLs you get in the client should be ``http://192.227.113.54:8787/serverpacks/...``
You may have to open the port 8787 in the firewall/router configuration to allow server pack downloads.

**Comment by ago1024** [comment]
Options with ``#`` are commented out and are not active. I've added the IP address from the log file to the settings so you can enable those options if needed. The default settings should work in most situations unless the server is behind a dialup router or a firewall.

**Comment by Kilem** [comment]
changeing the port got it, Thsnk you so much, you have patron, or paypal?  I would like to send a lil thank you donation for all your hard work.

**Comment by ago1024** [comment]
Great.

The paypal address is paypal.me/ago1024

**Comment by Tokeiito** [comment]
@ago1024 consider adding that to repositories description or so. :) Transforming coffee to code is not only time but also coffee consuming process.
