### ISSUE TITLE
In Game Map

### ISSUE THREAD

**Issue by griebo** [ago1024/WurmServerModLauncher#48]
hi there!

Sorry to bother ya, but I saw you helped Kilem with his in-game map. I was wondering if you could take a look at mine and help me troubleshoot. Kilem and I spent a few hours trying to get it to go.

I run with the host PingPerfect.
Also, I use the hitching post mod and that works/runs fine. I've included the files I use and the logs in a zip folder

Any advice you could give would be greatly appreciated!
Thanks,
Tony

[New folder (2).zip](https://github.com/ago1024/WurmServerModLauncher/files/1693651/New.folder.2.zip)

**Comment by ago1024** [comment]
A jar file is effectively a zip not a rar archive.
Please try with the repackaged pingperfect.jar file: [pingperfect.zip](https://github.com/ago1024/WurmServerModLauncher/files/1693662/pingperfect.zip)

**Comment by griebo** [comment]
Brilliant! Working great. Does that mean I should zip it first and then rename the .zip to .jar?

**Comment by ago1024** [comment]
yes. that's probably the easiest option

**Comment by griebo** [comment]
Great, thank you for your very fast replies and your help!
