### ISSUE TITLE
Shared ClassLoader doesn't support loading of Resources from mod jars

### ISSUE THREAD

**Issue by whisper2shade** [ago1024/WurmServerModLauncher#51]
Hi,
When using shared class loader, there is no way for a mod to load a .properties file from the mod jar.
I'm trying to create a localizable mod, but i can't load the messages_xx.properties files. 
Unfortunately, I need the shared classloader to hook into some classes manually so resource loading falls apart.

Thanks

**Comment by Goldenflamer** [comment]
SharedClassLoader also breaks the CallbackAPI

https://forum.wurmonline.com/index.php?/topic/133085-released-server-mod-loader-priest-crops-seasons-server-packs-bag-of-holding/&do=findComment&comment=1715732
