### ISSUE TITLE
Ingame map - Necroing

### ISSUE THREAD

**Issue by Arathok** [ago1024/WurmServerModLauncher#55]
Hello! New Wurm Server Admin here...
I followed the surrounding information and got my serverlog to say it made a pack.
Now my client.log doesn't seem to want to download the according pack.
Any help with setting this up would be greatly appreciated i will gladly provide any information you need!

EDIT1 i left the httpserver.config as is, do i need to set ips and ports in there?

**Comment by ago1024** [comment]
Does any of this help; https://github.com/ago1024/WurmServerModLauncher/wiki/Custom-maps#trouble-shooting

**Comment by Arathok** [comment]
Hello thanks for answering let me go through the single entries of that
**- The server address for the httpserver mod (previously for serverpacks mod) can be configured with the "publicServerAddress" setting in httpserver.config (or serverpacks.config).**

i've set the adress to the normal adress player will connec to (i hope thats correct) and to port 3750 and also opened the port on the firewall on my server.
yields: https://pastebin.com/82YEzevN  no line about getting a pack

**- The fixed port can be selected with the "serverPort" setting.** 
i left that line commented out, because the port is set by the gui, correct?

**- The interface for the serverpacks server can be selected with the "internalServerAddress" setting.**
i am unsure what to set there so i left it commented out

**- You can also use a real web server to handle the downloads. Setup the server to handle all pack download urls and set "publicServerAddress" and "publicServerPort" to the web server.**
i dont even know what that means.

**-Make sure the client serverpacks mod is installed**
serverpacks is installed


**The Download URL contains http://0.0.0.0/...
Either set the servers external address to your computers IP address or use that IP address as "publicServerAddress" in the httpserver (or serverpacks) configuration.**

dont know where the download url would show up. what would i set that adress to? my public ipv4 of my home pc?

If you need any more logs/files/answers i'll be happy to provide. Thanks for helping me out here!

**Comment by Arathok** [comment]
okay i've setup my port and ip and got the following messages in my log now:

[05:48:57 PM] INFORMATION org.gotti.wurmonline.clientmods.serverpacks.ServerPacksMod: Got server pack A0553A65523FE3159852CCAF022C54E021E81492 (http://173.249.0.230:3750/serverpacks/A0553A65523FE3159852CCAF022C54E021E81492?prepend)
[05:48:58 PM] INFORMATION org.gotti.wurmonline.clientmods.serverpacks.ServerPacksMod: Got server pack E5925B2787037226E7CAEEDA094B8ED0BA1CC62F (http://173.249.0.230:3750/serverpacks/E5925B2787037226E7CAEEDA094B8ED0BA1CC62F?prepend)

but then 

[05:49:00 PM] SCHWERWIEGEND org.gotti.wurmonline.clientmods.serverpacks.ServerPacksMod: Connection refused: connect
[05:49:00 PM] SCHWERWIEGEND org.gotti.wurmonline.clientmods.serverpacks.ServerPacksMod: Connection refused: connect

the server firewall is setup to allow communication through that port

**Comment by Arathok** [comment]
Update 2. I've got the packs now, but the ingame map shown is still "Ocrea"

**Comment by Arathok** [comment]
Update 3:
I've got it working now!
You absolutely need to check your wurmlogin.db to have the correct map name!
In httpserver.config make sure you use the fixed port setting and set to any port on your server.
(using the use next free port option wasn't working for me as i have a strict firewall setup)
Open that specific port in both directions on your firewall.

Thats what i did to make it work!
