### ISSUE TITLE
Priests cant improve items

### ISSUE THREAD

**Issue by Arathok** [ago1024/WurmServerModLauncher#56]
Hello!
I've basically left all the options in the .config as vanilla as possible.
my priests on the server cant improve items.
do i have to remove all the restrictions via the config to make improving possible? from the wiki i gathered, that even with restrictions in place priests would be able to improve items

**Comment by Darinth** [comment]
Are you by chance interested in PRs to resolve this and/or other issues with SpellMod?

**Comment by Arathok** [comment]
well im not a modder, so....

**Comment by Darinth** [comment]
FYI, you do have to remove all priest restrictions to remove the imping restrictions. Sorry I didn't come back and post, I kind of forgot. I did update the wiki back when I made the discovery. I'd actually prefer it the other way, but ohh well.

**Comment by Arathok** [comment]
All good man, your mod is still awesome!

**Comment by Darinth** [comment]
I just want to be clear that I am not the author, I just happened to notice it and then went and checked the code to confirm and since the wiki is publicly modifiable I went ahead and updated it. :)
