### ISSUE TITLE
linux instructions please

### ISSUE THREAD

**Issue by loganer** [ago1024/WurmServerModLauncher#6]
going to get the main info out of the way...
OS: Linux Mint 1.7.3 Cinnamon 64-bit
Cinnamon Version: 2.8.6
Linux Kernal: 3.16.0-38-generic
processor: Intel Core 2 Duo CPU E6550 @ 2.33GHz x2
memory: 3.7 GiB
hard drives 1693.6GB
Graphics Card NVIDIA Corporation GF119 [GeForce GT 610]
,ok now that i got that out of the way,
can you please make a tutorial to install this mod loader from fresh installation of wurm unlimited?

**Comment by aschmois** [comment]
There's a modlauncher.sh included in the zip file. A simple drag drop of the zipped contents and running the .sh file should be more than enough to get the mod loader running on linux. The mod loader is pure java so running it shouldn't have any different effects than on a Windows machine.

**Comment by Tokeiito** [comment]
This issue can be marked as closed as instructions were introduced in README.
